FROM golang:1.23.4-alpine3.20 as builder
WORKDIR /usr/src/app
COPY /app .
#RUN go mod download
RUN go build fullcycle.go


FROM scratch
WORKDIR /app
COPY --from=builder /usr/src/app .
CMD ["/app/fullcycle"]

